version: "3.8"

services:
  signalk:
    image: signalk/signalk-server:latest
    container_name: signalk
    restart: unless-stopped
    ports:
      - "80:3000"  # SignalK Web UI
    volumes:
      - ${MARINE_DATA}/signalk:/home/node/.signalk
    environment:
      - NODE_ENV=production
    privileged: true

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ${MARINE_DATA}/influx:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=signalk
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=changeme
      - INFLUXDB_HTTP_AUTH_ENABLED=true

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ${MARINE_DATA}/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=changeme
